-- Read-only check: select the current application database before running.
-- All 95 supplied Net IDs; returns only non-ACTIVE matches and missing IDs.
-- No customer data is changed. Empty results mean all supplied IDs match ACTIVE rows.
SELECT requested.net_id AS requested_net_id,
       c.internet_customer_id, c.customer_code, c.status AS current_status,
       CASE WHEN c.internet_customer_id IS NULL THEN 'NOT FOUND'
            ELSE 'STATUS MISMATCH' END AS result
FROM (
SELECT 'tn.ruchitaa' AS net_id
UNION ALL
SELECT 'tn.r.giri'
UNION ALL
SELECT 'tn.satheesvaran'
UNION ALL
SELECT 'tn.dhanasingh.d'
UNION ALL
SELECT 'tn.vinodh.v56'
UNION ALL
SELECT 'tn.janakiraman.t66'
UNION ALL
SELECT 'tn.balaji.g54'
UNION ALL
SELECT 'tn.samuel.i87'
UNION ALL
SELECT 'tn.logambiga'
UNION ALL
SELECT 'tn.sandhiya.s77'
UNION ALL
SELECT 'tn.mangayarkarasi.s56'
UNION ALL
SELECT 'tn.haja.91'
UNION ALL
SELECT 'tn.natarajan.g46'
UNION ALL
SELECT 'tn.naveen.g78'
UNION ALL
SELECT 'tn.rajan.a55'
UNION ALL
SELECT 'tn.bastin.d'
UNION ALL
SELECT 'tn.saravanakumaran.r56'
UNION ALL
SELECT 'tn.jeyapalan'
UNION ALL
SELECT 'tn.lakshminarayanan.78'
UNION ALL
SELECT 'tn.joseph.m56'
UNION ALL
SELECT 'tn.vasantha.am'
UNION ALL
SELECT 'tn.moorthy.munusamy'
UNION ALL
SELECT 'tn.yuvaraj.r56'
UNION ALL
SELECT 'tn.antonyraj.l'
UNION ALL
SELECT 'tn.monika.p44'
UNION ALL
SELECT 'tn.rajesh.kuppan'
UNION ALL
SELECT 'tn.karthick.r78'
UNION ALL
SELECT 'tn.muthumanikandan.01'
UNION ALL
SELECT 'tn.ganesan.v5'
UNION ALL
SELECT 'tn.shivatanners'
UNION ALL
SELECT 'tn.velayudham.d77'
UNION ALL
SELECT 'tn.lavanya.35'
UNION ALL
SELECT 'tn.weslybrown'
UNION ALL
SELECT 'tn.vishnupriya.m45'
UNION ALL
SELECT 'tn.rajarajeshwari.91'
UNION ALL
SELECT 'tn.muniyaswamy'
UNION ALL
SELECT 'tn.sivalingam.46'
UNION ALL
SELECT 'tn.meena.sk34'
UNION ALL
SELECT 'tn.karthik.256'
UNION ALL
SELECT 'tn.parthasarathy.d77'
UNION ALL
SELECT 'tn.bakkiyalakshmi.b'
UNION ALL
SELECT 'tn.karthick.g88'
UNION ALL
SELECT 'tn.sirajideen'
UNION ALL
SELECT 'tn.mohammed.matheen'
UNION ALL
SELECT 'tn.kalaivanan.kge'
UNION ALL
SELECT 'tn.jagadeesh.g57'
UNION ALL
SELECT 'tn.rajavel.r55'
UNION ALL
SELECT 'tn.sakthivelan.r78'
UNION ALL
SELECT 'tn.vidhyasekar.m33'
UNION ALL
SELECT 'tn.baskaran.g67'
UNION ALL
SELECT 'tn.meena.s76'
UNION ALL
SELECT 'tn.muthupandian.g55'
UNION ALL
SELECT 'tn.krishnan.r33'
UNION ALL
SELECT 'tn.parthiban.kannan'
UNION ALL
SELECT 'tn.ramesh.077'
UNION ALL
SELECT 'tn.rajendran.prakash'
UNION ALL
SELECT 'tn.ramalingam.v89'
UNION ALL
SELECT 'tn.lakshmi.m57'
UNION ALL
SELECT 'tn.ashra'
UNION ALL
SELECT 'tn.mutharasu.p'
UNION ALL
SELECT 'tn.devi.m56'
UNION ALL
SELECT 'tn.senthil.kl'
UNION ALL
SELECT 'tn.sheela.r88'
UNION ALL
SELECT 'tn.cathrine.ks'
UNION ALL
SELECT 'tn.suresh.pranav'
UNION ALL
SELECT 'tn.mpltechnologies'
UNION ALL
SELECT 'tn.gowtham.r67'
UNION ALL
SELECT 'tn.rajasekar.88'
UNION ALL
SELECT 'tn.palanivel.78'
UNION ALL
SELECT 'tn.bhuvaneswari.k45'
UNION ALL
SELECT 'tn.manivasan.02'
UNION ALL
SELECT 'tn.premalatha.k67'
UNION ALL
SELECT 'tn.meena.s77'
UNION ALL
SELECT 'tn.anandhraj.p'
UNION ALL
SELECT 'tn.saidbabu'
UNION ALL
SELECT 'tn.indimica'
UNION ALL
SELECT 'tn.pushpa.s67'
UNION ALL
SELECT 'tn.venkatesan.09'
UNION ALL
SELECT 'tn.jaganathan.k12'
UNION ALL
SELECT 'tn.venkataraman.kr'
UNION ALL
SELECT 'tn.manivasan.01'
UNION ALL
SELECT 'tn.nrkfreight'
UNION ALL
SELECT 'tn.mohammed.ab'
UNION ALL
SELECT 'tn.japanlab'
UNION ALL
SELECT 'tn.gli'
UNION ALL
SELECT 'tn.umapathy.k19'
UNION ALL
SELECT 'tn.noushad'
UNION ALL
SELECT 'tn.dhana.mo'
UNION ALL
SELECT 'tn.sarath.kr'
UNION ALL
SELECT 'tn.prabakaran.b8'
UNION ALL
SELECT 'tn.kumaran.sathya'
UNION ALL
SELECT 'tn.jenifa'
UNION ALL
SELECT 'tn.loganathan.selva'
UNION ALL
SELECT 'tn.balaji.pd'
UNION ALL
SELECT 'tn.sarbu'
) requested
LEFT JOIN internet_customers c
  ON LOWER(TRIM(CONVERT(c.net_id USING utf8mb4))) COLLATE utf8mb4_unicode_ci
   = CONVERT(requested.net_id USING utf8mb4) COLLATE utf8mb4_unicode_ci
WHERE c.internet_customer_id IS NULL OR c.status IS NULL OR c.status <> 'ACTIVE'
ORDER BY requested.net_id, c.internet_customer_id;
