import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';
import { FormArray, FormBuilder, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { InternetCustomerServices } from '../../services/internet-customer-services';
import { CommonMethods } from '../../shared/common-methods';

@Component({selector:'app-internet-customer-form',imports:[CommonModule,ReactiveFormsModule,RouterLink],templateUrl:'./internet-customer-form.html',styleUrl:'./internet-customer-form.scss'})
export class InternetCustomerForm {
  form!:FormGroup; lookups:any={}; id=0; areas:any[]=[]; streets:any[]=[];
  readonly monthNames=['January','February','March','April','May','June','July','August','September','October','November','December'];
  readonly today=new Date(Date.now()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,10);
  constructor(private fb:FormBuilder,private api:InternetCustomerServices,private route:ActivatedRoute,private router:Router,private common:CommonMethods){this.id=Number(this.route.snapshot.paramMap.get('id')||0);this.build();}
  get packages(){return this.form.get('packages') as FormArray} get routers(){return this.form.get('routers') as FormArray} get materials(){return this.form.get('materials') as FormArray}
  build(){this.form=this.fb.group({network_type:['KRISHI',Validators.required],full_name:['',Validators.required],net_id:['',Validators.required],network_password:[''],door_no:['',Validators.required],location_id:[null,Validators.required],area_id:[null,Validators.required],street_id:[null,Validators.required],state:['Tamil Nadu',Validators.required],city:['Chennai',Validators.required],pincode:[''],mobile_no:['',[Validators.required,Validators.pattern(/^\d{10}$/)]],alternate_mobile_no:['',Validators.pattern(/^\d{10}$/)],aadhaar_no:['',Validators.pattern(/^\d{12}$/)],source_name:['Direct',Validators.required],installed_by_employee_id:[null,Validators.required],installed_date:[this.today,Validators.required],status:['ACTIVE'],packages:this.fb.array([this.packageRow()]),routers:this.fb.array([this.routerRow()]),connection:this.fb.group({connection_date:[this.today,Validators.required],connection_type:['NEW'],connection_charge:[0],connection_discount:[0],labour_service_charge:[0],remarks:['']}),materials:this.fb.array([this.materialRow()]),subscription:this.fb.group({month:[new Date().getMonth()+1],year:[new Date().getFullYear()],period:['DAYS'],number_of_days:[0],collect_date:[this.today],start_date:[this.today],expiry_date:[this.today],subscription_amount:[0]}),account:this.fb.group({router_amount:[0],router_discount:[0],connection_amount:[0],connection_discount:[0],labor_amount:[0],material_cost:[0],material_discount:[0],subscription_amount:[0],overall_discount:[0],customer_paid_amount:[0],grand_total:[0],balance_amount:[0],account_status:['PENDING']})});
    this.form.get('location_id')?.valueChanges.subscribe(id=>{this.areas=(this.lookups.areas||[]).filter((x:any)=>Number(x.location_id)===Number(id));this.form.patchValue({area_id:null,street_id:null});});
    this.form.get('area_id')?.valueChanges.subscribe(id=>{this.streets=(this.lookups.streets||[]).filter((x:any)=>Number(x.area_id)===Number(id));this.form.patchValue({street_id:null});});
    this.form.get('installed_date')?.valueChanges.subscribe(v=>{this.form.get('connection.connection_date')?.setValue(v,{emitEvent:false});this.packages.controls.forEach((_,i)=>this.calculatePackage(i));});
    this.form.get('network_type')?.valueChanges.subscribe(network=>{this.packages.controls.forEach((row,i)=>{const selected=(this.lookups.packages||[]).find((x:any)=>Number(x.package_id)===Number(row.get('package_id')?.value));if(selected?.internet_network_type&&selected.internet_network_type!==network)row.patchValue({package_id:null,base_price:0,gst_percent:0,package_price:0,amount:0},{emitEvent:false});this.calculatePackage(i);});});
  }
  ngOnInit(){this.api.getLookups().subscribe({next:r=>{this.lookups=r;this.applyLoggedInstaller();if(this.id)this.load();},error:e=>this.common.handleError(e)});}
  applyLoggedInstaller(){if(this.lookups.is_admin===false)this.form.patchValue({installed_by_employee_id:this.lookups.logged_in_employee_id,installed_date:this.today},{emitEvent:false});}
  filteredPackages(){const network=this.form.get('network_type')?.value;return (this.lookups.packages||[]).filter((x:any)=>!x.internet_network_type||x.internet_network_type===network);}
  packageRow(x:any={}){return this.fb.group({package_id:[x.package_id||null,Validators.required],base_price:[x.base_price||0],gst_percent:[x.gst_percent||0],package_price:[x.total_price||x.package_price||0],start_date:[this.date(x.start_date)||this.today],end_date:[this.date(x.end_date)||this.today],amount:[x.amount||0]});}
  routerRow(x:any={}){return this.fb.group({router_type:[x.router_type||'NEW'],product_id:[x.product_id||null,Validators.required],hsn_code:[x.hsn_code||''],qty:[x.qty||1],unit:[x.unit||'PCS'],rate:[x.rate||0],amount:[x.amount||0]});}
  materialRow(x:any={}){return this.fb.group({product_id:[x.product_id||null],item_name:[x.item_name||''],qty:[x.qty||1],unit:[x.unit||'PCS'],unit_rate:[x.unit_rate||0],amount:[x.amount||0]});}
  addPackage(){this.packages.push(this.packageRow())} addRouter(){this.routers.push(this.routerRow())} addMaterial(){this.materials.push(this.materialRow())}
  remove(array:FormArray,i:number){if(array.length>1)array.removeAt(i);this.total();}
  selectPackage(i:number){const row=this.packages.at(i);const id=Number(row.get('package_id')?.value);if(this.packages.controls.some((r,n)=>n!==i&&Number(r.get('package_id')?.value)===id)){row.patchValue({package_id:null,base_price:0,gst_percent:0,package_price:0,amount:0});return this.common.handleError({error:{message:'Duplicate internet packages are not allowed'}});}const p=(this.lookups.packages||[]).find((x:any)=>Number(x.package_id)===id);row.patchValue({base_price:Number(p?.price)||0,gst_percent:Number(p?.gst_percent)||0,package_price:Number(p?.total_price)||0},{emitEvent:false});this.calculatePackage(i);}
  calculatePackage(i:number){const row=this.packages.at(i),start=new Date(`${this.form.get('installed_date')?.value||this.today}T00:00:00Z`),end=new Date(start),network=this.form.get('network_type')?.value;if(network==='KRISHI'){if(start.getUTCDate()>15)end.setUTCMonth(end.getUTCMonth()+1);end.setUTCDate(15);}else end.setUTCDate(end.getUTCDate()+29);const days=Math.round((end.getTime()-start.getTime())/86400000)+1,price=Math.round(Number(row.get('package_price')?.value)||0),dim=new Date(start.getUTCFullYear(),start.getUTCMonth()+1,0).getDate(),amount=network==='KRISHI'?price/dim*days:price;row.patchValue({package_price:price,start_date:this.date(start),end_date:this.date(end),amount:Math.round(amount)},{emitEvent:false});this.total();}
  selectRouter(i:number){const row=this.routers.at(i),id=Number(row.get('product_id')?.value);if(this.routers.controls.some((r,n)=>n!==i&&Number(r.get('product_id')?.value)===id)){row.patchValue({product_id:null,hsn_code:'',rate:0,amount:0});return this.common.handleError({error:{message:'Duplicate routers are not allowed'}});}const p=(this.lookups.routers||[]).find((x:any)=>Number(x.product_id)===id);row.patchValue({hsn_code:p?.hsn_code||'',unit:p?.unit||'PCS',rate:Number(p?.selling_price)||0},{emitEvent:false});this.calcRouter(i);}
  calcRouter(i:number){const r=this.routers.at(i);r.get('amount')?.setValue(Math.round((Number(r.get('qty')?.value)||0)*(Number(r.get('rate')?.value)||0)),{emitEvent:false});this.total();}
  selectMaterial(i:number){const r=this.materials.at(i),id=Number(r.get('product_id')?.value);if(this.materials.controls.some((x,n)=>n!==i&&Number(x.get('product_id')?.value)===id)){r.patchValue({product_id:null,item_name:'',unit_rate:0,amount:0});return this.common.handleError({error:{message:'Duplicate used materials are not allowed'}});}const p=(this.lookups.products||[]).find((x:any)=>Number(x.product_id)===id);r.patchValue({item_name:p?.product_name||'',unit:p?.unit||'PCS',unit_rate:Number(p?.selling_price)||0},{emitEvent:false});this.calcMaterial(i);}
  calcMaterial(i:number){const r=this.materials.at(i);r.get('amount')?.setValue(Math.round((Number(r.get('qty')?.value)||0)*(Number(r.get('unit_rate')?.value)||0)),{emitEvent:false});this.total();}
  total(){const sum=(a:FormArray,k:string)=>a.controls.reduce((s,r)=>s+(Number(r.get(k)?.value)||0),0),c=this.form.get('connection')!,a=this.form.get('account')!,s=this.form.get('subscription')!;const routerAmount=sum(this.routers,'amount'),connectionAmount=Number(c.get('connection_charge')?.value)||0,connectionDiscount=Number(c.get('connection_discount')?.value)||0,laborAmount=Number(c.get('labour_service_charge')?.value)||0,materialCost=sum(this.materials,'amount'),subscriptionAmount=sum(this.packages,'amount'),routerDiscount=Number(a.get('router_discount')?.value)||0,materialDiscount=Number(a.get('material_discount')?.value)||0,overallDiscount=Number(a.get('overall_discount')?.value)||0;const first=this.packages.at(0),startDate=first?.get('start_date')?.value||this.form.get('installed_date')?.value||this.today,expiryDate=first?.get('end_date')?.value||startDate,start=new Date(`${startDate}T00:00:00Z`),end=new Date(`${expiryDate}T00:00:00Z`),days=Math.max(Math.round((end.getTime()-start.getTime())/86400000)+1,0);s.patchValue({month:start.getUTCMonth()+1,year:start.getUTCFullYear(),period:'DAYS',number_of_days:days,collect_date:this.today,start_date:startDate,expiry_date:expiryDate,subscription_amount:Number(subscriptionAmount.toFixed(2))},{emitEvent:false});const grand=Math.max(routerAmount-routerDiscount+connectionAmount-connectionDiscount+laborAmount+materialCost-materialDiscount+subscriptionAmount-overallDiscount,0),paid=Number(a.get('customer_paid_amount')?.value)||0,balance=Math.max(grand-paid,0),status=balance<=0?'PAID':paid>0?'PARTIAL':'PENDING';a.patchValue({router_amount:Number(routerAmount.toFixed(2)),connection_amount:Number(connectionAmount.toFixed(2)),connection_discount:Number(connectionDiscount.toFixed(2)),labor_amount:Number(laborAmount.toFixed(2)),material_cost:Number(materialCost.toFixed(2)),subscription_amount:Number(subscriptionAmount.toFixed(2)),grand_total:Number(grand.toFixed(2)),balance_amount:Number(balance.toFixed(2)),account_status:status},{emitEvent:false});}
  load(){this.api.getCustomer(this.id).subscribe({next:r=>{this.form.patchValue({...r.customer,connection:r.connections?.[0]||{},account:r.account||{}},{emitEvent:false});this.applyLoggedInstaller();this.areas=(this.lookups.areas||[]).filter((x:any)=>Number(x.location_id)===Number(r.customer.location_id));this.streets=(this.lookups.streets||[]).filter((x:any)=>Number(x.area_id)===Number(r.customer.area_id));for(const [array,data,make] of [[this.packages,r.packages,(x:any)=>this.packageRow(x)],[this.routers,r.routers,(x:any)=>this.routerRow(x)],[this.materials,r.materials,(x:any)=>this.materialRow(x)]] as any[]){array.clear();(data?.length?data:[{}]).forEach((x:any)=>array.push(make(x)));}this.packages.controls.forEach((_,i)=>this.calculatePackage(i));this.total();},error:e=>this.common.handleError(e)});}
  save(){if(this.form.invalid){this.form.markAllAsTouched();return;}this.total();const call=this.id?this.api.updateCustomer(this.id,this.form.getRawValue()):this.api.addCustomer(this.form.getRawValue());call.subscribe({next:r=>{this.common.handleTokenAndMessage(r);this.router.navigateByUrl('/internet/customers');},error:e=>this.common.handleError(e)});}
  date(v:any){if(!v)return'';const d=new Date(v);return Number.isNaN(d.getTime())?'':d.toISOString().slice(0,10);}
}
