import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';
import { FormArray, FormBuilder, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { InternetCustomerServices } from '../../services/internet-customer-services';
import { CommonMethods } from '../../shared/common-methods';
import { SelectModule } from 'primeng/select';

@Component({selector:'app-internet-customer-form',imports:[CommonModule,ReactiveFormsModule,RouterLink,SelectModule],templateUrl:'./internet-customer-form.html',styleUrls:['./internet-customer-form.scss','./router-category.scss']})
export class InternetCustomerForm {
  form!:FormGroup; lookups:any={}; id=0; saving=false; private previousSubscriptionPaid=0; areas:any[]=[]; streets:any[]=[];
  readonly monthNames=['January','February','March','April','May','June','July','August','September','October','November','December'];
  readonly today=new Date(Date.now()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,10);
  constructor(private fb:FormBuilder,private api:InternetCustomerServices,private route:ActivatedRoute,private router:Router,private common:CommonMethods){this.id=Number(this.route.snapshot.paramMap.get('id')||0);this.build();}
  get packages(){return this.form.get('packages') as FormArray} get routers(){return this.form.get('routers') as FormArray} get materials(){return this.form.get('materials') as FormArray}
  build(){this.form=this.fb.group({network_type:['KRISHI',Validators.required],full_name:['',Validators.required],email:['',this.id ? [Validators.email] : [Validators.required,Validators.email]],net_id:['',Validators.required],network_password:[''],door_no:['',Validators.required],location_id:[null,Validators.required],area_id:[null,Validators.required],street_id:[null,Validators.required],state:['Tamil Nadu',Validators.required],city:['Chennai',Validators.required],pincode:[''],mobile_no:['',[Validators.required,Validators.pattern(/^\d{10}$/)]],alternate_mobile_no:['',Validators.pattern(/^\d{10}$/)],aadhaar_no:['',Validators.pattern(/^\d{12}$/)],source_name:['Direct',Validators.required],installed_by_employee_id:[null,Validators.required],installed_date:[this.today,Validators.required],status:['ACTIVE'],packages:this.fb.array([this.packageRow()]),routers:this.fb.array([this.routerRow()]),connection:this.fb.group({connection_date:[this.today,Validators.required],connection_type:['NEW'],connection_charge:[0],connection_discount:[0],labour_service_charge:[0],remarks:['']}),materials:this.fb.array([this.materialRow()]),subscription:this.subscriptionRow(),account:this.fb.group({router_amount:[0],router_discount:[0],connection_amount:[0],connection_discount:[0],labor_amount:[0],material_cost:[0],material_discount:[0],subscription_amount:[0],overall_discount:[0],customer_paid_amount:[0],grand_total:[0],balance_amount:[0],account_status:['PENDING']})});
    this.form.get('location_id')?.valueChanges.subscribe(id=>{this.areas=(this.lookups.areas||[]).filter((x:any)=>Number(x.location_id)===Number(id));this.form.patchValue({area_id:null,street_id:null});});
    this.form.get('area_id')?.valueChanges.subscribe(id=>{this.streets=(this.lookups.streets||[]).filter((x:any)=>Number(x.area_id)===Number(id));this.form.patchValue({street_id:null});});
    this.form.get('installed_date')?.valueChanges.subscribe(v=>{this.form.get('connection.connection_date')?.setValue(v,{emitEvent:false});this.packages.controls.forEach((_,i)=>this.calculatePackage(i));});
    this.form.get('network_type')?.valueChanges.subscribe(network=>{this.packages.controls.forEach((row,i)=>{const selected=(this.lookups.packages||[]).find((x:any)=>Number(x.package_id)===Number(row.get('package_id')?.value));if(selected&&this.packageNetwork(selected)!==String(network||'').toUpperCase())row.patchValue({package_id:null,base_price:0,gst_percent:this.id?0:18,gst_amount:0,sgst_amount:0,cgst_amount:0,package_price:0,amount:0},{emitEvent:false});this.calculatePackage(i);});});
    this.form.get('installed_by_employee_id')?.valueChanges.subscribe(()=>{if(this.lookups.is_admin===true){this.routers.controls.forEach(r=>r.patchValue({product_id:null,router_stock_key:null,material_movement_id:null,hsn_code:'',rate:0,discount:0,amount:0},{emitEvent:false}));this.total();}});
  }
  ngOnInit(){this.api.getLookups().subscribe({next:r=>{this.lookups={...r,routers:this.id?r.routers:[...(r.routers||[]),...(r.issued_routers||[])]};this.applyLoggedInstaller();if(this.id)this.load();else {this.form.get('subscription')?.patchValue({collected_by_employee_id:r.logged_in_employee_id,payment_mapped_employee_id:r.logged_in_employee_id},{emitEvent:false});this.calculateSubscription();}},error:e=>this.common.handleError(e)});}
  applyLoggedInstaller(){if(this.lookups.is_admin===false)this.form.patchValue({installed_by_employee_id:this.lookups.logged_in_employee_id,installed_date:this.today},{emitEvent:false});}
  packageNetwork(item:any){return String(item?.provider_category||item?.internet_network_type||'').trim().toUpperCase();}
  filteredPackages(){const network=String(this.form.get('network_type')?.value||'').toUpperCase();return (this.lookups.packages||[]).filter((x:any)=>this.packageNetwork(x)===network);}
  filteredRouters(i?:number){const employeeId=Number(this.lookups.is_admin===false?this.lookups.logged_in_employee_id:this.form.get('installed_by_employee_id')?.value);return (this.lookups.routers||[]).filter((x:any)=>employeeId>0 && Number(x.employee_id)===employeeId && (this.id || i===undefined || x.router_type===this.routers.at(i).get('router_type')?.value));}
  packageRow(x:any={}){return this.fb.group({package_id:[x.package_id||null,Validators.required],base_price:[x.base_price||0],gst_percent:[{value:this.id ? x.gst_percent||0 : 18,disabled:!this.id}],gst_amount:[0],sgst_percent:[{value:9,disabled:true}],sgst_amount:[{value:0,disabled:true}],cgst_percent:[{value:9,disabled:true}],cgst_amount:[{value:0,disabled:true}],package_price:[x.total_price||x.package_price||0],start_date:[this.date(x.start_date)||this.today],end_date:[this.date(x.end_date)||this.today],amount:[x.amount||0]});}
  routerRow(x:any={}){return this.fb.group({router_stock_key:[x.product_id?`stock:${x.product_id}`:null],material_movement_id:[null],router_type:[x.router_type||'NEW'],usage_category:[x.usage_category||'CUSTOMER_PAID'],product_id:[x.product_id||null],hsn_code:[x.hsn_code||''],qty:[x.qty||1],unit:[x.unit||'PCS'],rate:[x.rate||0],discount:[x.discount||0],amount:[x.amount||0]});}
  materialRow(x:any={}){return this.fb.group({product_id:[x.product_id||null],item_name:[x.item_name||''],qty:[x.qty||1],unit:[x.unit||'PCS'],unit_rate:[x.unit_rate||0],discount:[x.discount||0],amount:[x.amount||0]});}
  addPackage(){this.packages.push(this.packageRow())} addRouter(){this.routers.push(this.routerRow())} addMaterial(){this.materials.push(this.materialRow())}
  remove(array:FormArray,i:number){if(array.length>1)array.removeAt(i);this.total();}
  selectPackage(i:number){const row=this.packages.at(i);const id=Number(row.get('package_id')?.value);if(this.packages.controls.some((r,n)=>n!==i&&Number(r.get('package_id')?.value)===id)){row.patchValue({package_id:null,base_price:0,gst_percent:this.id?0:18,gst_amount:0,sgst_amount:0,cgst_amount:0,package_price:0,amount:0});return this.common.handleError({error:{message:'Duplicate internet packages are not allowed'}});}const p=(this.lookups.packages||[]).find((x:any)=>Number(x.package_id)===id);row.patchValue({base_price:Number(p?.price)||0,gst_percent:this.id ? Number(p?.gst_percent)||0 : 18,package_price:this.id ? Number(p?.total_price)||0 : this.round((Number(p?.price)||0)*1.18),gst_amount:this.round((Number(p?.price)||0)*.18),sgst_amount:this.round((Number(p?.price)||0)*.09),cgst_amount:this.round((Number(p?.price)||0)*.09)},{emitEvent:false});this.calculatePackage(i);}
  calculatePackage(i:number){if(!this.id){this.calculateSubscription();return;}const row=this.packages.at(i),start=new Date(`${this.form.get('installed_date')?.value||this.today}T00:00:00Z`),end=new Date(start),network=this.form.get('network_type')?.value;if(network==='KRISHI'){if(start.getUTCDate()>15)end.setUTCMonth(end.getUTCMonth()+1);end.setUTCDate(15);}else end.setUTCDate(end.getUTCDate()+29);const days=Math.round((end.getTime()-start.getTime())/86400000)+1,price=Math.round(Number(row.get('package_price')?.value)||0),dim=new Date(start.getUTCFullYear(),start.getUTCMonth()+1,0).getDate(),amount=network==='KRISHI'?price/dim*days:price;row.patchValue({package_price:price,start_date:this.date(start),end_date:this.date(end),amount:Math.round(amount)},{emitEvent:false});this.total();}
  selectRouter(i:number){const row=this.routers.at(i),key=row.get('router_stock_key')?.value,selected=this.filteredRouters(i).find((x:any)=>x.stock_key===key),id=Number(selected?.product_id||row.get('product_id')?.value);if(this.routers.controls.some((r,n)=>n!==i&&Number(r.get('product_id')?.value)===id)){row.patchValue({product_id:null,router_stock_key:null,material_movement_id:null,hsn_code:'',rate:0,discount:0,amount:0});return this.common.handleError({error:{message:'Duplicate routers are not allowed'}});}const p=selected||this.filteredRouters(i).find((x:any)=>Number(x.product_id)===id);row.patchValue({product_id:id||null,material_movement_id:p?.material_movement_id||null,hsn_code:p?.hsn_code||'',unit:p?.unit||'PCS',rate:Number(p?.selling_price)||0},{emitEvent:false});this.calcRouter(i);}
  calcRouter(i:number){if(!this.id){const r=this.routers.at(i),free=r.get('usage_category')?.value==='FREE_USE',gross=this.round(Number(r.get('qty')?.value)*Number(r.get('rate')?.value)),discount=free?0:Number(r.get('discount')?.value)||0;r.patchValue({...(free?{rate:0}:{}),discount,amount:free?0:this.round(Math.max(gross-discount,0))},{emitEvent:false});this.total();return;}const r=this.routers.at(i),gross=Math.round((Number(r.get('qty')?.value)||0)*(Number(r.get('rate')?.value)||0)),discount=r.get('usage_category')?.value==='FREE_USE'?gross:0;r.patchValue({discount,amount:Math.max(gross-discount,0)},{emitEvent:false});this.total();}
  selectMaterial(i:number){const r=this.materials.at(i),id=Number(r.get('product_id')?.value);if(this.materials.controls.some((x,n)=>n!==i&&Number(x.get('product_id')?.value)===id)){r.patchValue({product_id:null,item_name:'',unit_rate:0,amount:0});return this.common.handleError({error:{message:'Duplicate used materials are not allowed'}});}const p=(this.lookups.products||[]).find((x:any)=>Number(x.product_id)===id);r.patchValue({item_name:p?.product_name||'',unit:p?.unit||'PCS',unit_rate:Number(p?.selling_price)||0},{emitEvent:false});this.calcMaterial(i);}
  calcMaterial(i:number){if(!this.id){const r=this.materials.at(i);r.patchValue({amount:this.round(Math.max(Number(r.get('qty')?.value)*Number(r.get('unit_rate')?.value)-(Number(r.get('discount')?.value)||0),0))},{emitEvent:false});this.total();return;}const r=this.materials.at(i);r.get('amount')?.setValue(Math.round((Number(r.get('qty')?.value)||0)*(Number(r.get('unit_rate')?.value)||0)),{emitEvent:false});this.total();}
  legacyTotal(){const sum=(a:FormArray,k:string)=>a.controls.reduce((s,r)=>s+(Number(r.get(k)?.value)||0),0),c=this.form.get('connection')!,a=this.form.get('account')!,s=this.form.get('subscription')!;const routerAmount=sum(this.routers,'amount'),routerDiscount=sum(this.routers,'discount'),connectionAmount=Number(c.get('connection_charge')?.value)||0,connectionDiscount=Number(c.get('connection_discount')?.value)||0,materialCost=sum(this.materials,'amount'),subscriptionAmount=sum(this.packages,'amount'),materialDiscount=Number(a.get('material_discount')?.value)||0,overallDiscount=Number(a.get('overall_discount')?.value)||0;const first=this.packages.at(0),startDate=first?.get('start_date')?.value||this.form.get('installed_date')?.value||this.today,expiryDate=first?.get('end_date')?.value||startDate,start=new Date(`${startDate}T00:00:00Z`),end=new Date(`${expiryDate}T00:00:00Z`),days=Math.max(Math.round((end.getTime()-start.getTime())/86400000)+1,0);s.patchValue({month:start.getUTCMonth()+1,year:start.getUTCFullYear(),period:'DAYS',number_of_days:days,collect_date:this.today,start_date:startDate,expiry_date:expiryDate,subscription_amount:Number(subscriptionAmount.toFixed(2))},{emitEvent:false});const grand=Math.max(routerAmount+connectionAmount-connectionDiscount+materialCost-materialDiscount+subscriptionAmount-overallDiscount,0),paid=Number(a.get('customer_paid_amount')?.value)||0,balance=Math.max(grand-paid,0);a.patchValue({router_amount:Number(routerAmount.toFixed(2)),router_discount:Number(routerDiscount.toFixed(2)),connection_amount:Number(connectionAmount.toFixed(2)),connection_discount:Number(connectionDiscount.toFixed(2)),labor_amount:0,material_cost:Number(materialCost.toFixed(2)),subscription_amount:Number(subscriptionAmount.toFixed(2)),grand_total:Number(grand.toFixed(2)),balance_amount:Number(balance.toFixed(2)),account_status:'PENDING'},{emitEvent:false});}
  load(){this.api.getCustomer(this.id).subscribe({next:r=>{this.form.patchValue({...r.customer,connection:r.connections?.[0]||{},account:r.account||{}},{emitEvent:false});this.applyLoggedInstaller();this.areas=(this.lookups.areas||[]).filter((x:any)=>Number(x.location_id)===Number(r.customer.location_id));this.streets=(this.lookups.streets||[]).filter((x:any)=>Number(x.area_id)===Number(r.customer.area_id));for(const [array,data,make] of [[this.packages,r.packages,(x:any)=>this.packageRow(x)],[this.routers,r.routers,(x:any)=>this.routerRow(x)],[this.materials,r.materials,(x:any)=>this.materialRow(x)]] as any[]){array.clear();(data?.length?data:[{}]).forEach((x:any)=>array.push(make(x)));}this.packages.controls.forEach((_,i)=>this.calculatePackage(i));this.total();},error:e=>this.common.handleError(e)});}
  save(){if(this.saving)return;this.total();if(this.form.invalid){this.form.markAllAsTouched();this.common.handleError({error:{message:'Please fill all required customer, package and subscription details'}});return;}this.total();if(!this.id && this.form.get('subscription.end_date')?.value<this.form.get('subscription.start_date')?.value){this.common.handleError({error:{message:'End date cannot be before start date'}});return;}this.saving=true;const call=this.id?this.api.updateCustomer(this.id,this.form.getRawValue()):this.api.addCustomer(this.form.getRawValue());call.subscribe({next:r=>{this.saving=false;this.common.handleTokenAndMessage(r);this.router.navigateByUrl('/internet/customers');},error:e=>{this.saving=false;this.common.handleError(e);}});}

  readonly years=Array.from({length:11},(_,i)=>new Date().getFullYear()-2+i);
  readonly periodValues=Array.from({length:12},(_,i)=>i+1);
  readonly dayValues=Array.from({length:31},(_,i)=>i+1);
  readonly freeValues=Array.from({length:13},(_,i)=>i);
  readonly freeDayValues=Array.from({length:32},(_,i)=>i);
  round(value:number){return Math.round((value+Number.EPSILON)*100)/100;}
  subscriptionRow(){const required=this.id?[]:[Validators.required];return this.fb.group({
    month:[new Date().getMonth()+1,required],year:[new Date().getFullYear(),required],
    period:['DAYS'],number_of_days:[0],expiry_date:[this.today],subscription_amount:[0],
    period_unit:['MONTH',required],period_value:[1,required],period_count:[1],free_period_value:[0,required],free_period_unit:['MONTH',required],
    start_date:[this.today,required],end_date:[this.today,required],collect_date:[this.today,required],
    paid_amount:[0,[...required,Validators.min(0)]],balance_amount:[0],payment_status:['PENDING',required],
    collected_by_employee_id:[null,required],renewed_by_value:['ADMIN',required],payment_mode:['CASH',required],
    payment_reference:['',required],payment_mapped_employee_id:[null,required]
  });}
  changePeriodUnit(free=false){this.form.get('subscription')?.patchValue(free?{free_period_value:0}:{period_value:1},{emitEvent:false});this.calculateSubscription();}
  changeSubscriptionMonth(){const s=this.form.get('subscription')!,v=s.value,start=new Date(Date.UTC(Number(v.year),Number(v.month)-1,this.form.get('network_type')?.value==='KRISHI'?16:1));s.patchValue({start_date:this.date(start)},{emitEvent:false});this.calculateSubscription();}
  calculateSubscription(){if(this.id)return;const s=this.form.get('subscription')!,v=s.value,start=new Date(`${v.start_date}T00:00:00Z`);if(!Number.isFinite(start.getTime()))return;
    const value=Number(v.period_value)||1,days=new Date(Date.UTC(start.getUTCFullYear(),start.getUTCMonth()+1,0)).getUTCDate(),count=v.period_unit==='YEAR'?value*12:v.period_unit==='DAYS'?value/days:value,free=Number(v.free_period_value)||0,krishi=this.form.get('network_type')?.value==='KRISHI',end=new Date(start);
    if(v.period_unit==='DAYS')end.setUTCDate(end.getUTCDate()+value-1);else if(krishi){end.setUTCMonth(end.getUTCMonth()+count);end.setUTCDate(15);}else end.setUTCDate(end.getUTCDate()+count*30-1);
    if(v.free_period_unit==='DAYS')end.setUTCDate(end.getUTCDate()+free);else if(krishi)end.setUTCMonth(end.getUTCMonth()+free*(v.free_period_unit==='YEAR'?12:1));else end.setUTCDate(end.getUTCDate()+free*(v.free_period_unit==='YEAR'?360:30));
    s.patchValue({month:start.getUTCMonth()+1,year:start.getUTCFullYear(),period_count:Number(count.toFixed(4)),end_date:this.date(end)},{emitEvent:false});this.total();
  }
  changeRenewedBy(){const s=this.form.get('subscription')!,v=s.value;s.patchValue({renewed_by_value:this.lookups.is_admin?v.renewed_by_value:'ADMIN',payment_mode:this.lookups.is_admin&&v.renewed_by_value==='CUSTOMER'?'DASHBOARD':['CASH','ACCOUNT'].includes(v.payment_mode)?v.payment_mode:'CASH'},{emitEvent:false});this.total();}
  changeSubscriptionStatus(){const s=this.form.get('subscription')!,status=s.get('payment_status')?.value,amount=Number(s.get('subscription_amount')?.value)||0;if(status==='PAID')s.patchValue({paid_amount:amount},{emitEvent:false});else if(status==='PENDING')s.patchValue({paid_amount:0},{emitEvent:false});this.total();}
  changeRouterType(i:number){this.routers.at(i).patchValue({product_id:null,router_stock_key:null,material_movement_id:null,hsn_code:'',rate:0,discount:0,amount:0},{emitEvent:false});this.total();}
  changeRouterCategory(i:number){if(this.id){this.calcRouter(i);return;}const row=this.routers.at(i);if(row.get('usage_category')?.value==='CUSTOMER_PAID'){const product=this.filteredRouters(i).find((x:any)=>Number(x.product_id)===Number(row.get('product_id')?.value));row.patchValue({rate:Number(product?.selling_price)||0,discount:0},{emitEvent:false});}this.calcRouter(i);}
  total(){if(this.id){this.legacyTotal();return;}const s=this.form.get('subscription')!,v=s.value,start=new Date(`${v.start_date}T00:00:00Z`);const days=Number.isFinite(start.getTime())?new Date(Date.UTC(start.getUTCFullYear(),start.getUTCMonth()+1,0)).getUTCDate():30,count=v.period_unit==='YEAR'?Number(v.period_value)*12:v.period_unit==='DAYS'?Number(v.period_value)/days:Number(v.period_value)||1;
    let subscriptionAmount=0;this.packages.controls.forEach(row=>{const amount=Math.round((Number(row.get('package_price')?.value)||0)*count);row.patchValue({amount,start_date:v.start_date,end_date:v.end_date},{emitEvent:false});subscriptionAmount+=amount;});
    const paid=Math.min(Math.max(Number(v.paid_amount)||0,0),subscriptionAmount),balance=subscriptionAmount-paid;
    s.patchValue({subscription_amount:subscriptionAmount,paid_amount:paid,balance_amount:balance,payment_status:balance<=0?'PAID':paid>0?'PARTIAL':'PENDING'},{emitEvent:false});
    const sum=(a:FormArray,k:string)=>this.round(a.controls.reduce((n,r)=>n+(Number(r.get(k)?.value)||0),0)),a=this.form.get('account')!,c=this.form.get('connection')!.value,routerAmount=sum(this.routers,'amount'),routerDiscount=sum(this.routers,'discount'),materialDiscount=sum(this.materials,'discount'),materialCost=this.round(sum(this.materials,'amount')+materialDiscount),labor=Number(c.labour_service_charge)||0;
    const onlinePaid=v.renewed_by_value==='CUSTOMER'&&v.payment_mode==='DASHBOARD'&&balance<=0,accountSubscription=onlinePaid?0:subscriptionAmount,accountSubscriptionPaid=onlinePaid?0:paid;
    const grand=this.round(Math.max(routerAmount+(Number(c.connection_charge)||0)-(Number(c.connection_discount)||0)+labor+materialCost-materialDiscount+accountSubscription-(Number(a.get('overall_discount')?.value)||0),0)),customerPaid=this.round(Math.min(Math.max((Number(a.get('customer_paid_amount')?.value)||0)+accountSubscriptionPaid-this.previousSubscriptionPaid,accountSubscriptionPaid),grand));this.previousSubscriptionPaid=accountSubscriptionPaid;
    a.patchValue({router_amount:routerAmount,router_discount:routerDiscount,connection_amount:Number(c.connection_charge)||0,connection_discount:Number(c.connection_discount)||0,labor_amount:labor,material_cost:materialCost,material_discount:materialDiscount,subscription_amount:accountSubscription,grand_total:grand,customer_paid_amount:customerPaid,balance_amount:this.round(Math.max(grand-customerPaid,0)),account_status:'PENDING'},{emitEvent:false});
  }
  date(v:any){if(!v)return'';const d=new Date(v);return Number.isNaN(d.getTime())?'':d.toISOString().slice(0,10);}
}
